<a href="https://colab.research.google.com/github/vinusmiles/GenAI/blob/main/GenAI_Twitter_Customer_Support_TextPreProcessing_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Data Load***

In [6]:
import pandas as pd

In [7]:
data=pd.read_csv("/content/drive/MyDrive/Data Science/GenAI by iNeuron/Assignment 1_twitter customer support/twcs/twcs.csv")
data.rename(columns={'text': 'review'}, inplace=True)

In [ ]:
data.head()

tweet_id   author_id  inbound                      created_at  \
0         1  sprintcare    False  Tue Oct 31 22:10:47 +0000 2017   
1         2      115712     True  Tue Oct 31 22:11:45 +0000 2017   
2         3      115712     True  Tue Oct 31 22:08:27 +0000 2017   
3         4  sprintcare    False  Tue Oct 31 21:54:49 +0000 2017   
4         5      115712     True  Tue Oct 31 21:49:35 +0000 2017   

                                              review response_tweet_id  \
0  @115712 I understand. I would like to assist y...                 2   
1      @sprintcare and how do you propose we do that               NaN   
2  @sprintcare I have sent several private messag...                 1   
3  @115712 Please send us a Private Message so th...                 3   
4                                 @sprintcare I did.                 4   

   in_response_to_tweet_id  
0                      3.0  
1                      1.0  
2                      4.0  
3                      5.0  
4                      6.0

In [ ]:
data.tail()

tweet_id   author_id  inbound                      created_at  \
2811769   2987947  sprintcare    False  Wed Nov 22 08:43:51 +0000 2017   
2811770   2987948      823869     True  Wed Nov 22 08:35:16 +0000 2017   
2811771   2812240      121673     True  Thu Nov 23 04:13:07 +0000 2017   
2811772   2987949      AldiUK    False  Wed Nov 22 08:31:24 +0000 2017   
2811773   2987950      823870     True  Tue Nov 21 22:01:04 +0000 2017   

                                                      text response_tweet_id  \
2811769  @823869 Hey, we'd be happy to look into this f...               NaN   
2811770  @115714 wtf!? I’ve been having really shitty s...           2987947   
2811771  @143549 @sprintcare You have to go to https://...               NaN   
2811772  @823870 Sounds delicious, Sarah! 😋 https://t.c...               NaN   
2811773  @AldiUK  warm sloe gin mince pies with ice cre...   2987951,2987949   

         in_response_to_tweet_id  
2811769                2987948.0  
2811770                      NaN  
2811771                2812239.0  
2811772                2987950.0  
2811773                      NaN

In [ ]:
data.sample(5)

tweet_id       author_id  inbound                      created_at  \
651791     439507  Safaricom_Care    False  Wed Oct 11 09:39:20 +0000 2017   
2184484   2346447      sainsburys    False  Tue Nov 28 15:19:55 +0000 2017   
1341524   1477358          463021     True  Thu Nov 02 22:10:51 +0000 2017   
1065198   1178367         AskAmex    False  Tue Oct 24 21:21:34 +0000 2017   
2018882   2176900      AmazonHelp    False  Sun Oct 29 08:28:00 +0000 2017   

                                                      text response_tweet_id  \
651791                         @219347 -(contd)advise. ^NP               NaN   
2184484  @678449 Thanks, could you DM us their barcode ...               NaN   
1341524  This seems totally legitimate... heads up @116...   1477357,1477359   
1065198  @397140 Hi there, you should receive your card...           1178368   
2018882  @638071 詳細をお知らせいただき、誠にありがとうございます。ご利用者様の貴重なご意見と...               NaN   

         in_response_to_tweet_id  
651791                  439506.0  
2184484                2346445.0  
1341524                      NaN  
1065198                1178366.0  
2018882                2176896.0

In [ ]:
# renaming the column "text" to review

data.rename(columns={'text': 'review'}, inplace=True)

# ***lower casing***

In [ ]:
data["review"][651791].lower()

'@219347 -(contd)advise. ^np'

In [ ]:
data.shape

(2811774, 7)

In [ ]:
data["review"]=data["review"].str.lower()

In [ ]:
data["review"][44005]

'@128435 1/2 understood. to help you further with your concern, can you provide us the service request number that was given to you? https://t.co/3qcaslfkay'

# ***Remove URLs***

In [ ]:
import re

In [ ]:
def remove_url(text):
    pattern=re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub("",text)

In [ ]:
print(data.columns)

Index(['tweet_id', 'author_id', 'inbound', 'created_at', 'review',
       'response_tweet_id', 'in_response_to_tweet_id'],
      dtype='object')


In [ ]:
data['review'] = data['review'].apply(remove_url)

In [ ]:
data['review'][2811772]

'@823870 sounds delicious, sarah! 😋 '

# ***Remove Punctuations***

In [ ]:
import string

string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
exclude = string.punctuation

In [ ]:
def remove_punc(text):
    for char in exclude:
        text=text.replace(char,"")
    return text

In [ ]:
data['review'] = data['review'].apply(remove_punc)

In [ ]:
chat_words={
    "LOL": "Laugh Out Loud",
    "BRB": "Be Right Back",
    "TTYL": "Talk To You Later",
    "BTW": "By The Way",
    "FYI": "For Your Information",
    "OMG": "Oh My God",
    "IDK": "I Don’t Know",
    "IMO": "In My Opinion",
    "IMHO": "In My Humble Opinion",
    "IRL": "In Real Life",
    "BFF": "Best Friends Forever",
    "SMH": "Shaking My Head",
    "TBH": "To Be Honest",
    "ROFL": "Rolling On the Floor Laughing",
    "TMI": "Too Much Information",
    "NP": "No Problem",
    "DM": "Direct Message",
    "ASAP": "As Soon As Possible",
    "GG": "Good Game",
    "TL;DR": "Too Long; Didn’t Read",
    "IKR": "I Know, Right?",
    "FWIW": "For What It’s Worth",
    "AFK": "Away From Keyboard",
    "NVM": "Never Mind",
    "YOLO": "You Only Live Once"
}

In [ ]:
chat_words["ASAP"]

'As Soon As Possible'

In [ ]:
def chat_conversion(text):
    new_text=[]
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [ ]:
data['review'] = data['review'].apply(chat_conversion)

# ***Spell correction***

In [ ]:
import textblob
from textblob import TextBlob

In [ ]:
text="this is my processing notebook pleae download this ntebook"

In [ ]:
txtblob=TextBlob(text)

In [ ]:
txtblob.correct().string

'this is my processing notebook please download this notebook'

# ***Stop word removal***

In [ ]:

import nltk

In [ ]:
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
stopwords.words("english")

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
def remove_stopwords(text):
    new_text=[]

    for word in text.split():
        if word in stopwords.words("english"):
            new_text.append("")
        else:
            new_text.append(word.strip())


    return " ".join(new_text).replace("   ","")

In [ ]:
data['review'][2811769]

"@823869 Hey, we'd be happy to look into this for you. Please send us a Direct Message, so that we can further assist you. -TN"

In [ ]:
data['review'][2811769] = remove_stopwords(data['review'][2811769])

<ipython-input-23-ea40eeed4a41>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['review'][2811769] = remove_stopwords(data['review'][2811769])


In [ ]:
data['review'][2811769]

"@823869 Hey, we'd  happy  look you. Please send us  Direct Message,assist you. -TN"

# ***Remove Emojis***

In [ ]:
!pip install emoji

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 421.5/421.5 kB 3.3 MB/s eta 0:00:00


In [ ]:
import emoji

In [ ]:
def remove_emoji(text):
    clean_text=emoji.demojize(text)
    return clean_text

In [ ]:
data['review'][2811772]

'@823870 Sounds delicious, Sarah! 😋 https://t.co/7uQPwyH1B6'

In [ ]:
data['review'][2811772]=remove_emoji(data['review'][2811772])

<ipython-input-24-29d4676faab3>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['review'][2811772]=remove_emoji(data['review'][2811772])


# ***All Text Pre Processing steps***

In [ ]:
data['review'][2811772] = data['review'][2811772].lower()

<ipython-input-12-b97199b37371>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['review'][2811772] = data['review'][2811772].lower()


In [ ]:
import re
data['review'][2811772] = remove_url(data['review'][2811772])

<ipython-input-17-ae360febffbe>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['review'][2811772] = remove_url(data['review'][2811772])


In [ ]:
data['review'][2811772] = remove_punc(data['review'][2811772])

<ipython-input-47-94ba2ef30be3>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['review'][2811772] = remove_punc(data['review'][2811772])


In [ ]:
data['review'][2811772] = remove_stopwords(data['review'][2811772])

<ipython-input-49-5648440741d7>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['review'][2811772] = remove_stopwords(data['review'][2811772])


In [ ]:
data['review'][2811772] = remove_emoji(data['review'][2811772])

<ipython-input-51-878dacb0ad77>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['review'][2811772] = remove_emoji(data['review'][2811772])


# ***Tokenization***

In [ ]:
import re

In [ ]:
data['review'][2811772]

'823870 sounds delicious sarah :face_savoring_food:'

In [ ]:
re.findall("[\w]+",data['review'][2811772])

['823870', 'sounds', 'delicious', 'sarah', 'face_savoring_food']

In [ ]:
import nltk
nltk.download("punkt")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [ ]:
word_tokenize(data['review'][2811772])

['@',
 '823870',
 'sounds',
 'delicious',
 ',',
 'sarah',
 '!',
 ':',
 'face_savoring_food',
 ':']

# ***One hot encoding***

In [ ]:
# Find the lengthiest record in the review column
lengthiest_record = data['review'].str.len().idxmax()
lengthiest_record_content = data.loc[lengthiest_record, 'review']

print(f"The lengthiest record is: '{lengthiest_record_content}' with a length of {len(lengthiest_record_content)} characters.")

The lengthiest record is: '@176042 @176031 @176045 @176044 @176047 @176048 @176049 @176046 @176043 @176050 @176029 @176030 @176025 @176027 @176051 @176026 @176041 @176052 @176036 @176037 @176038 @176032 @176033 @1616 @1617 @176028 @176035 @176034 @176039 @1618 @176040 @115996 The funny thing about them is they go out riot and destroy property and get arrested and don’t think for one second they just screwed up their life being a criminal! But it keeps making me money as I go after criminals which adds to my bank account! My play money' with a length of 513 characters.


In [ ]:
# Find the index of the lengthiest record in the specified column
max_length_index = data['review'].str.len().idxmax()

# Retrieve the content of the lengthiest record
lengthiest_record_content = data.loc[max_length_index, 'review']

# Output the result
print(f"The lengthiest record is at row index {max_length_index} (0-based indexing): '{lengthiest_record_content}'")
print(f"Length: {len(lengthiest_record_content)} characters.")

The lengthiest record is at row index 217042 (0-based indexing): '@176042 @176031 @176045 @176044 @176047 @176048 @176049 @176046 @176043 @176050 @176029 @176030 @176025 @176027 @176051 @176026 @176041 @176052 @176036 @176037 @176038 @176032 @176033 @1616 @1617 @176028 @176035 @176034 @176039 @1618 @176040 @115996 The funny thing about them is they go out riot and destroy property and get arrested and don’t think for one second they just screwed up their life being a criminal! But it keeps making me money as I go after criminals which adds to my bank account! My play money'
Length: 513 characters.


In [ ]:
data['review'][217042]

'@176042 @176031 @176045 @176044 @176047 @176048 @176049 @176046 @176043 @176050 @176029 @176030 @176025 @176027 @176051 @176026 @176041 @176052 @176036 @176037 @176038 @176032 @176033 @1616 @1617 @176028 @176035 @176034 @176039 @1618 @176040 @115996 The funny thing about them is they go out riot and destroy property and get arrested and don’t think for one second they just screwed up their life being a criminal! But it keeps making me money as I go after criminals which adds to my bank account! My play money'

In [ ]:
import spacy

# Load the English NLP model from spacy
nlp = spacy.load("en_core_web_sm")

In [ ]:
def tokenize_text(text):
    # Process the text with the spacy model
    doc = nlp(text)

    # Extract tokens from the processed document
    tokens = [token.text for token in doc]

    return tokens

In [ ]:
tokens=tokenize_text(data['review'][217042])

In [ ]:
for word in tokens:
    print(word)

@176042
@176031
@176045
@176044
@176047
@176048
@176049
@176046
@176043
@176050
@176029
@176030
@176025
@176027
@176051
@176026
@176041
@176052
@176036
@176037
@176038
@176032
@176033
@1616
@1617
@176028
@176035
@176034
@176039
@1618
@176040
@115996
The
funny
thing
about
them
is
they
go
out
riot
and
destroy
property
and
get
arrested
and
do
n’t
think
for
one
second
they
just
screwed
up
their
life
being
a
criminal
!
But
it
keeps
making
me
money
as
I
go
after
criminals
which
adds
to
my
bank
account
!
My
play
money


# ***Stemming and Lemmatization***

In [ ]:
from nltk.stem import PorterStemmer

def stemming(text):
    obj=PorterStemmer()

    stem_word=[obj.stem(word) for word in text.split()]

    return stem_word

In [ ]:
stemming(data['review'][217042])

['@176042',
 '@176031',
 '@176045',
 '@176044',
 '@176047',
 '@176048',
 '@176049',
 '@176046',
 '@176043',
 '@176050',
 '@176029',
 '@176030',
 '@176025',
 '@176027',
 '@176051',
 '@176026',
 '@176041',
 '@176052',
 '@176036',
 '@176037',
 '@176038',
 '@176032',
 '@176033',
 '@1616',
 '@1617',
 '@176028',
 '@176035',
 '@176034',
 '@176039',
 '@1618',
 '@176040',
 '@115996',
 'the',
 'funni',
 'thing',
 'about',
 'them',
 'is',
 'they',
 'go',
 'out',
 'riot',
 'and',
 'destroy',
 'properti',
 'and',
 'get',
 'arrest',
 'and',
 'don’t',
 'think',
 'for',
 'one',
 'second',
 'they',
 'just',
 'screw',
 'up',
 'their',
 'life',
 'be',
 'a',
 'criminal!',
 'but',
 'it',
 'keep',
 'make',
 'me',
 'money',
 'as',
 'i',
 'go',
 'after',
 'crimin',
 'which',
 'add',
 'to',
 'my',
 'bank',
 'account!',
 'my',
 'play',
 'money']

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
from nltk.stem import WordNetLemmatizer

def lammatization(text):
    words=text.split()

    lemmetizer=WordNetLemmatizer()

    lemetized_word=[lemmetizer.lemmatize(word) for word in words]

    return lemetized_word

In [ ]:
lammatization(data['review'][217042])

['@176042',
 '@176031',
 '@176045',
 '@176044',
 '@176047',
 '@176048',
 '@176049',
 '@176046',
 '@176043',
 '@176050',
 '@176029',
 '@176030',
 '@176025',
 '@176027',
 '@176051',
 '@176026',
 '@176041',
 '@176052',
 '@176036',
 '@176037',
 '@176038',
 '@176032',
 '@176033',
 '@1616',
 '@1617',
 '@176028',
 '@176035',
 '@176034',
 '@176039',
 '@1618',
 '@176040',
 '@115996',
 'The',
 'funny',
 'thing',
 'about',
 'them',
 'is',
 'they',
 'go',
 'out',
 'riot',
 'and',
 'destroy',
 'property',
 'and',
 'get',
 'arrested',
 'and',
 'don’t',
 'think',
 'for',
 'one',
 'second',
 'they',
 'just',
 'screwed',
 'up',
 'their',
 'life',
 'being',
 'a',
 'criminal!',
 'But',
 'it',
 'keep',
 'making',
 'me',
 'money',
 'a',
 'I',
 'go',
 'after',
 'criminal',
 'which',
 'add',
 'to',
 'my',
 'bank',
 'account!',
 'My',
 'play',
 'money']

# ***BOW***

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
BOW=CountVectorizer()

In [7]:
document_matrix=BOW.fit_transform(data['review'])

In [ ]:
document_matrix

<2811774x1388583 sparse matrix of type '<class 'numpy.int64'>'
	with 50114726 stored elements in Compressed Sparse Row format>

In [8]:
BOW.vocabulary_

{'115712': 18623,
 'understand': 1267300,
 'would': 1304868,
 'like': 1065614,
 'to': 1249357,
 'assist': 838650,
 'you': 1328090,
 'we': 1295261,
 'need': 1106973,
 'get': 973573,
 'into': 1019273,
 'private': 1158114,
 'secured': 1206901,
 'link': 1066067,
 'further': 965479,
 'sprintcare': 1223090,
 'and': 831035,
 'how': 1000925,
 'do': 918408,
 'propose': 1159391,
 'that': 1243347,
 'have': 991460,
 'sent': 1208064,
 'several': 1209094,
 'messages': 1086833,
 'no': 1113355,
 'one': 1130373,
 'is': 1022114,
 'responding': 1186371,
 'as': 837493,
 'usual': 1272381,
 'please': 1151152,
 'send': 1207837,
 'us': 1271716,
 'message': 1086816,
 'so': 1218731,
 'can': 873545,
 'just': 1038390,
 'click': 884896,
 'at': 839090,
 'the': 1243551,
 'top': 1250568,
 'of': 1126106,
 'your': 1328371,
 'profile': 1158816,
 'did': 911974,
 'gain': 969641,
 'details': 909670,
 'about': 814322,
 'account': 815295,
 'worst': 1304541,
 'customer': 898016,
 'service': 1208645,
 '115713': 18624,
 'this':

In [9]:
document_matrix[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [10]:
document_matrix[1].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [11]:
document_matrix[2].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [12]:
document_matrix[3].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

# ***N-grams***

In [13]:
bigram=CountVectorizer(ngram_range=(2,2))

In [14]:
bigramvocab=bigram.fit_transform(data["review"])

In [15]:
bigram.vocabulary_

{'115712 understand': 36500,
 'understand would': 6158896,
 'would like': 6478151,
 'like to': 4228240,
 'to assist': 6008434,
 'assist you': 1997742,
 'you we': 6542913,
 'we would': 6352036,
 'would need': 6478267,
 'need to': 4574056,
 'to get': 6014727,
 'get you': 3574123,
 'you into': 6536223,
 'into private': 3976787,
 'private secured': 5073353,
 'secured link': 5439959,
 'link to': 4238304,
 'to further': 6014550,
 'further assist': 3534618,
 'sprintcare and': 5663108,
 'and how': 1858689,
 'how do': 3840126,
 'do you': 3117561,
 'you propose': 6539378,
 'propose we': 5102647,
 'we do': 6349860,
 'do that': 3116937,
 'sprintcare have': 5663558,
 'have sent': 3716886,
 'sent several': 5465941,
 'several private': 5490483,
 'private messages': 5073252,
 'messages and': 4421120,
 'and no': 1862154,
 'no one': 4624390,
 'one is': 4772556,
 'is responding': 4012035,
 'responding as': 5289403,
 'as usual': 1970721,
 '115712 please': 36499,
 'please send': 5000317,
 'send us': 546135

In [16]:
trigram=CountVectorizer(ngram_range=(3,3))

In [17]:
trigramdata=trigram.fit_transform(data["review"])

In [18]:
trigram.vocabulary_

{'115712 understand would': 72492,
 'understand would like': 15841606,
 'would like to': 16976378,
 'like to assist': 9485948,
 'to assist you': 15240106,
 'assist you we': 3375131,
 'you we would': 17245646,
 'we would need': 16466432,
 'would need to': 16977312,
 'need to get': 10527169,
 'to get you': 15315254,
 'get you into': 7042135,
 'you into private': 17175921,
 'into private secured': 8644466,
 'private secured link': 12215053,
 'secured link to': 13136641,
 'link to further': 9517843,
 'to further assist': 15310993,
 'sprintcare and how': 13795273,
 'and how do': 2819052,
 'how do you': 7920692,
 'do you propose': 5741575,
 'you propose we': 17204365,
 'propose we do': 12292424,
 'we do that': 16438269,
 'sprintcare have sent': 13796796,
 'have sent several': 7509226,
 'sent several private': 13222074,
 'several private messages': 13310436,
 'private messages and': 12214793,
 'messages and no': 10031405,
 'and no one': 2848261,
 'no one is': 10687308,
 'one is responding': 1

In [19]:
mix=CountVectorizer(ngram_range=(1,2))

In [21]:
mix_vocab=mix.fit_transform(data["review"])

In [22]:
mix.vocabulary_

{'115712': 55118,
 'understand': 7425038,
 'would': 7782102,
 'like': 5287473,
 'to': 7253245,
 'assist': 2834922,
 'you': 7857967,
 'we': 7644292,
 'need': 5677872,
 'get': 4540756,
 'into': 4993463,
 'private': 6231114,
 'secured': 6646791,
 'link': 5302886,
 'further': 4499921,
 '115712 understand': 55124,
 'understand would': 7426197,
 'would like': 7783020,
 'like to': 5293855,
 'to assist': 7257792,
 'assist you': 2836393,
 'you we': 7871004,
 'we would': 7647298,
 'would need': 7783136,
 'need to': 5681030,
 'to get': 7264085,
 'get you': 4547697,
 'you into': 7864314,
 'into private': 4996061,
 'private secured': 6231468,
 'secured link': 6646861,
 'link to': 5304372,
 'to further': 7263908,
 'further assist': 4500098,
 'sprintcare': 6885494,
 'and': 2678506,
 'how': 4840171,
 'do': 4030850,
 'propose': 6261988,
 'that': 7103458,
 'sprintcare and': 6886199,
 'and how': 2689725,
 'how do': 4841052,
 'do you': 4035970,
 'you propose': 7867469,
 'propose we': 6262039,
 'we do': 76

# ***tf-Idf***

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
tfidf=TfidfVectorizer()

In [9]:
tfidf.fit_transform(data["review"][0:100]).toarray()

array([[0.        , 0.        , 0.22351201, ..., 0.        , 0.21186179,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.17705388,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [10]:
tfidf.get_feature_names_out()

array(['0g98rtnxpk', '10', '115712', '115713', '115714', '115715',
       '115716', '115717', '115718', '115719', '115720', '115721',
       '115722', '115723', '115724', '115725', '115726', '115727',
       '115728', '115729', '115730', '115731', '115732', '115733',
       '115734', '115735', '115736', '115737', '115738', '115739',
       '115740', '115741', '115742', '115743', '171', '1hmw7qxweh', '20',
       '28', '31', '3pm', '5shdrmlc1t', '60', '7tjdvpzlwn', 'aa', 'able',
       'about', 'access', 'account', 'acct', 'acm', 'actually', 'address',
       'adult', 'again', 'all', 'alone', 'already', 'also', 'altfbaztyc',
       'although', 'an', 'and', 'any', 'anything', 'apologies',
       'apologize', 'app', 'are', 'area', 'arrived', 'as', 'ask_spectrum',
       'askplaystation', 'assist', 'assumption', 'at', 'authenticating',
       'away', 'awesome', 'ax7w1dx3y9', 'back', 'bars', 'basically',
       'bcw', 'be', 'because', 'becky', 'been', 'best', 'better',
       'between', 'bi

In [11]:
tfidf.idf_

array([4.92197334, 4.92197334, 4.22882616, 4.22882616, 4.51650823,
       4.92197334, 4.0056826 , 4.92197334, 4.92197334, 4.51650823,
       4.92197334, 3.82336105, 4.0056826 , 3.82336105, 4.92197334,
       4.51650823, 4.92197334, 4.92197334, 4.92197334, 4.92197334,
       4.92197334, 4.51650823, 4.92197334, 4.92197334, 4.92197334,
       4.92197334, 4.92197334, 4.51650823, 4.92197334, 4.92197334,
       4.92197334, 4.51650823, 4.92197334, 4.51650823, 4.92197334,
       4.92197334, 4.92197334, 4.92197334, 4.92197334, 4.92197334,
       4.92197334, 4.92197334, 4.92197334, 4.51650823, 4.92197334,
       4.22882616, 4.92197334, 3.31253542, 4.22882616, 4.22882616,
       4.92197334, 4.92197334, 4.92197334, 4.92197334, 3.41789594,
       4.51650823, 4.92197334, 4.51650823, 4.92197334, 4.92197334,
       4.22882616, 2.57059808, 4.92197334, 4.92197334, 4.51650823,
       4.92197334, 4.22882616, 3.21722524, 4.51650823, 4.92197334,
       4.51650823, 3.66921037, 4.92197334, 4.0056826 , 4.92197